name: Ruff Code Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ruff
      run: |
        apt-get install -y pipx
        pipx ensurepath
        pipx install ruff

    - name: Run Ruff check
      run: |
        ruff check .

